### ISSUE TITLE
cranelift "simplejit" backend has been renamed "jit"

### ISSUE THREAD

**Issue by pchickey** [sunfishcode/simplejit-demo#50]
https://github.com/bytecodealliance/wasmtime/pull/2479

The code and docs should be updated to reflect this change.

**Comment by ghost** [comment]
👋 @pchickey, I'd love to take this on as a foot-in-the-door to future contributions hopefully :) I can get a PR up soon if that sounds good. Happy holidays!

**Comment by sunfishcode** [comment]
@rgrmrts Yes, that sounds great!

**Comment by ghost** [comment]
Cool! Just opened the PR (#53) but trying to build it I'm realizing this change https://github.com/bytecodealliance/wasmtime/pull/2479 hasn't yet updated the crates on https://crates.io/crates/cranelift-simplejit

I'm unsure what the process to update the crate to the new name is but probably something that requires a permissioned member?

**EDIT:** was just looking into this and sounds like a new crate for `cranelift-jit` will need to be created and published to since renames are not possible (makes sense).
